
import React from 'react';
import type { SyntheticDataSet, SyntheticPatient } from '../types';
import { UsersIcon, AlertTriangleIcon, InfoIcon } from './icons';

const SyntheticDataDisplay: React.FC<{ dataSet: SyntheticDataSet }> = ({ dataSet }) => {
    const { cohortParameters, syntheticPatients } = dataSet;
    const metricKeys = syntheticPatients.length > 0 
        ? Object.keys(syntheticPatients[0].keyMetrics) 
        : [];
    
    return (
        <div className="space-y-6 animate-fade-in">
            {/* Disclaimer */}
            <div className="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-800 p-4 rounded-md" role="alert">
                <div className="flex items-center">
                    <AlertTriangleIcon className="h-6 w-6 text-yellow-600 mr-3" />
                    <div>
                        <p className="font-bold">Synthetic Data Warning</p>
                        <p className="text-sm">This is high-fidelity, privacy-preserving synthetic data generated by the ELYSIUM Sandbox. It is **NOT** real patient data and must **ONLY** be used for research, model training, and bias mitigation purposes.</p>
                    </div>
                </div>
            </div>

            {/* Header */}
            <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm">
                <div className="flex justify-between items-start">
                    <div>
                        <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
                            <UsersIcon className="w-8 h-8 text-blue-600" />
                            Synthetic Patient Cohort
                        </h2>
                        <p className="text-slate-700 mt-1">
                            Generated a cohort of <span className="font-semibold">{cohortParameters.patientCount}</span> synthetic patients
                            for <span className="font-semibold">"{cohortParameters.primaryCondition}"</span>,
                            aged <span className="font-semibold">{cohortParameters.ageRange}</span>.
                        </p>
                    </div>
                </div>
            </div>

            {/* Data Table */}
            <div className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-slate-200">
                        <thead className="bg-slate-50">
                            <tr>
                                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-700 uppercase tracking-wider">Patient ID</th>
                                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-700 uppercase tracking-wider">Age</th>
                                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-700 uppercase tracking-wider">Sex</th>
                                {metricKeys.map(key => (
                                     <th key={key} scope="col" className="px-6 py-3 text-left text-xs font-medium text-slate-700 uppercase tracking-wider">{key}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-slate-200">
                            {syntheticPatients.map((patient) => (
                                <tr key={patient.patientId} className="hover:bg-slate-50">
                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">{patient.patientId}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-700">{patient.age}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-700">{patient.assignedSex}</td>
                                     {metricKeys.map(key => (
                                        <td key={key} className="px-6 py-4 whitespace-nowrap text-sm text-slate-700">{patient.keyMetrics[key]}</td>
                                    ))}
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

             {/* Provenance Footer */}
            <div className="text-center text-xs text-slate-500 mt-6 p-3 bg-slate-100 rounded-md flex items-center justify-center gap-2 flex-wrap">
                <InfoIcon className="w-4 h-4" />
                <span><span className="font-semibold">Analysis ID:</span> {dataSet.analysisId}</span>
                 <span className="text-slate-300 hidden md:inline">|</span>
                <span><span className="font-semibold">Generated:</span> {new Date(dataSet.timestamp).toLocaleString()}</span>
                <span className="text-slate-300 hidden md:inline">|</span>
                <span><span className="font-semibold">Model:</span> {dataSet.modelUsed}</span>
            </div>
        </div>
    );
};

export default SyntheticDataDisplay;